### Calculate delays between src and mic's
R.Sprik 6/6/2024

In [1]:
import numpy as np 
import matplotlib.pyplot as plt

### select a working backend
#%matplotlib widget 
%matplotlib qt5

### position of single source and microphone

In [2]:
#position of single source and microphone, units meter
pmic = np.array([0.0,0.0,0.0])  # xyz microphone
psrc = np.array([0.0,0.0, 0.5]) #     point source

def distance(psrc,pmic):
    pdif = psrc-pmic
    dd = np.linalg.norm(pdif)
    return(dd)

print(f"mic {pmic}")
print(f"src {psrc}")

dis = distance(psrc, pmic)
print(f"dis {dis}")

mic [0. 0. 0.]
src [0.  0.  0.5]
dis 0.5


### single source to square microphone array

In [11]:
### source position
psrc = np.array([0.05, 0.0, 0.1]) # xyz point source

### square microphone array
nx = 4; ny = 4
apmic       = np.zeros((nx,ny,3))
micsep      = 0.042  #distance between microphones in array
zmicshft    = 0.0    #z-plane microphone array

for ix in range(nx):
    x = (ix-(nx-1)/2)*micsep
    for iy in range(ny):
        y = (iy-(ny-1)/2)*micsep
        apmic[ix,iy,:]= [x,y,zmicshft]
print(f"Mic positions\n {apmic}")
        
# scatter plot of the mic array ans source
plt.close("all")
fig = plt.figure(10)
ax = fig.add_subplot(projection='3d')
ax.scatter(apmic[:,:,0], apmic[:,:,1], apmic[:,:,2], marker='+')
ax.scatter(psrc[0], psrc[1], psrc[2], marker='o')
ax.set_xlabel('X (m)')
ax.set_ylabel('Y (m)')
ax.set_zlabel('Z (m)')
plt.show() 

# calculate distance and plot
adist = np.zeros((nx,ny))
for ix in range(0,nx):
    for iy in range(0,ny):
        adist[ix,iy]= distance(apmic[ix,iy,:], psrc)
print(f"\nSrc to Mic distance:\n {adist}")

plt.figure(20)
plt.imshow(adist)
plt.colorbar()
plt.title("Distance src to microphone array (m)")
plt.show()

vair = 340.0  #speed of sound in air
plt.figure(30)
plt.imshow(adist/vair)
plt.colorbar()
plt.title("Delay src to microphone array (s)")
plt.show()

#resolution at a sampling rate Fs
Fs = 48000.0
dt = 1/Fs
print(f"\nResolution dt = {dt}s at {Fs}Hz sampling")

#delays in sample dt 
plt.figure(40)
adeldt = (adist/vair)/dt  
plt.imshow(adeldt)
plt.colorbar()
plt.title(f"Delay in sample times at Fs={Fs} (Hz)")
plt.show()

"""
#phase delays for a given frequency
plt.figure(50)
freq = 1.0e3
lamb = vair/freq
aphase = (adist/lamb)*360.0 #in degrees
plt.imshow(aphase)
plt.colorbar()
plt.title(f"Phase (deg) at {freq}Hz (wavelength={lamb}m)")
plt.show()
"""

Mic positions
 [[[-0.063 -0.063  0.   ]
  [-0.063 -0.021  0.   ]
  [-0.063  0.021  0.   ]
  [-0.063  0.063  0.   ]]

 [[-0.021 -0.063  0.   ]
  [-0.021 -0.021  0.   ]
  [-0.021  0.021  0.   ]
  [-0.021  0.063  0.   ]]

 [[ 0.021 -0.063  0.   ]
  [ 0.021 -0.021  0.   ]
  [ 0.021  0.021  0.   ]
  [ 0.021  0.063  0.   ]]

 [[ 0.063 -0.063  0.   ]
  [ 0.063 -0.021  0.   ]
  [ 0.063  0.021  0.   ]
  [ 0.063  0.063  0.   ]]]

Src to Mic distance:
 [[0.16351758 0.15234829 0.15234829 0.16351758]
 [0.13787676 0.12442669 0.12442669 0.13787676]
 [0.12169634 0.10621676 0.10621676 0.12169634]
 [0.11890332 0.10300485 0.10300485 0.11890332]]

Resolution dt = 2.0833333333333333e-05s at 48000.0Hz sampling


'\n#phase delays for a given frequency\nplt.figure(50)\nfreq = 1.0e3\nlamb = vair/freq\naphase = (adist/lamb)*360.0 #in degrees\nplt.imshow(aphase)\nplt.colorbar()\nplt.title(f"Phase (deg) at {freq}Hz (wavelength={lamb}m)")\nplt.show()\n'